# -*- coding: utf-8 -*-
"""Copy of The last

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZzK542rF0cNsBZ9Hk3j52jd4tF3Ehhz
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
nahiyan1402_anemiadataset_path = kagglehub.dataset_download('nahiyan1402/anemiadataset')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline
from sklearn import preprocessing
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.preprocessing import LabelEncoder,StandardScaler,MinMaxScaler
#importing all the required ML packages
from sklearn.linear_model import LogisticRegression #logistic regression
from sklearn import svm #support vector Machine
from sklearn.ensemble import RandomForestClassifier #Random Forest
from sklearn.neighbors import KNeighborsClassifier #KNN
from sklearn.naive_bayes import GaussianNB #Naive bayes
from sklearn.tree import DecisionTreeClassifier #Decision Tree
from sklearn.model_selection import train_test_split #training and testing data split
from sklearn import metrics #accuracy measure
from sklearn.metrics import confusion_matrix, accuracy_score ,precision_score, recall_score,f1_score,classification_report,roc_curve, auc, precision_recall_curve, recall_score, average_precision_score, precision_recall_fscore_support
from sklearn.model_selection import validation_curve
from sklearn import linear_model, tree, ensemble
from sklearn.naive_bayes import MultinomialNB
from IPython import display
from sklearn.model_selection import KFold #for K-fold cross validation
from sklearn.model_selection import cross_val_score #score evaluation
from sklearn.model_selection import cross_val_predict #prediction
from sklearn.model_selection import StratifiedKFold
from sklearn.manifold import TSNE
import xgboost as xg

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import os
data = pd.read_csv(os.path.join(nahiyan1402_anemiadataset_path, 'Anemia_Dataset.csv'))

data.head()

data.dtypes

le = LabelEncoder()
data["anaemic_encoded"] = le.fit_transform(data['Anaemic'])
data["sex_encoded"] = le.fit_transform(data['Sex'])

data.dtypes

data.columns

data.isnull().sum()

"""Let's visualize the data and see which features could be used the predict the result label


"""

data.head()

data.tail()

data.size

data.info()

data.columns

data.shape

data.dtypes.value_counts()

data.isnull().sum() #checking for total null values

# data.value_counts()
data["Anaemic"].value_counts()

data.describe()

"""Let's see how many people have anemia in the dataset. It will give an idea whether the data is balanced or imbalanced


"""

#f,ax=plt.subplots(1,2,figsize=(18,8))
#data['Anaemic'].value_counts().plot.pie(explode=[0,0.1],autopct='%1.1f%%',ax=ax[0],shadow=True)
#ax[0].set_title('had anemia')
#ax[0].set_ylabel('')
#sns.countplot('Anaemic',data=data,ax=ax[1])
#ax[1].set_title('had anemia')
#plt.show()
sns.countplot(x="Anaemic", data=data)
data.loc[:,'Anaemic'].value_counts()

"""Categorical Feature: Gender


"""

data.groupby(['Sex','Anaemic'])['Anaemic'].count()

sns.countplot(x ='Sex', hue = "Anaemic", data = data)

sns.barplot(x='Sex',y="%Blue pixel",hue="Anaemic",data=data)

sns.barplot(x="Sex",y="%Blue pixel",data=data)

sns.barplot(x="Sex",y="%Green pixel",data=data,hue="Anaemic")

sns.barplot(x="Sex",y="Hb",data=data,hue="Anaemic")

sns.distplot(data["Hb"])

sns.distplot(data["%Green pixel"])

sns.boxplot(data["Hb"])

#we removed outliers from the data set
data.shape

#now we will the correlation matrix in order to get the relation
sns.heatmap(data[['   %Red Pixel', '%Green pixel', '%Blue pixel', 'Hb', 'anaemic_encoded', 'sex_encoded']].corr(),annot=True,cmap="coolwarm")

#from the above we can say that mostly
sns.pairplot(data,hue="Anaemic")

f,ax=plt.subplots(1,2,figsize=(10,7))
data[['Sex','Hb']].groupby(['Sex']).mean().plot.bar(ax=ax[0])
ax[0].set_title('Having Anemia vs Hb')
sns.countplot(x='Sex',hue='Hb',data=data,ax=ax[1])
ax[1].set_title('Sex:Having Anemia vs Not Having Anemia')
plt.show()

"""Continious Feature: Hemoglobin


"""

# See the min, max, mean values
print('The highest hemoglobin was of:',data['Hb'].max())
print('The lowest hemoglobin was of:',data['Hb'].min())
print('The average hemoglobin in the data:',data['Hb'].mean())

fig,(ax1,ax2)=plt.subplots(1,2,figsize=(13,5))
data_len=data[data['Anaemic']=='Yes']['Hb'].value_counts()
ax1.hist(data_len,color='red')
ax1.set_title('Having anemia')
data_len=data[data['Anaemic']=='No']['Hb'].value_counts()
ax2.hist(data_len,color='green')
ax2.set_title('NOT Having anemia')
fig.suptitle('Hemoglobin Levels')
plt.show()

"""Continious Feature: MCH (Mean Corpuscular Hemoglobin)


"""

# See the min, max, mean values
print('The highest MCH was of:',data['Hb'].max())
print('The lowest MCH was of:',data['Hb'].min())
print('The average MCH in the data:',data['Hb'].mean())

# See the min, max, mean values
print('The highest HB was of:',data['Hb'].max())
print('The lowest Hb was of:',data['Hb'].min())
print('The average Hb in the data:',data['Hb'].mean())

"""Continious Feature: MCV (Mean Corpuscular Volume)


"""

# See the min, max, mean values
print('The highest Hb was of:',data['Hb'].max())
print('The lowest Hb was of:',data['Hb'].min())
print('The average Hb in the data:',data['Hb'].mean())

fig,(ax1,ax2)=plt.subplots(1,2,figsize=(13,5))
data_len=data[data['Anaemic']=='Yes']['%Blue pixel'].value_counts()
ax1.hist(data_len,color='red')
ax1.set_title('Having anemia')
data_len=data[data['Anaemic']=='No']['%Blue pixel'].value_counts()
ax2.hist(data_len,color='green')
ax2.set_title('NOT Having anemia')
fig.suptitle('%Blue pixel Levels')
plt.show()

"""1.Feature Engineering and Data Cleaning

We need to convert the continous values into categorical values by either Binning or Normalisation. Binning and normalisation both will be used in this section i.e group a range of ages into a single bin or assign them a single value.
"""

sns.heatmap(data[['   %Red Pixel', '%Green pixel', '%Blue pixel', 'Hb', 'anaemic_encoded', 'sex_encoded']].corr(),annot=True,cmap='RdYlGn',linewidths=0.2) #data.corr()-->correlation matrix
fig=plt.gcf()
fig.set_size_inches(10,8)
plt.show()

d = preprocessing.normalize(data.iloc[:,2:5], axis=0)
scaled_df = pd.DataFrame(d, columns=["%Red Pixel","%Green pixel", "%Blue pixel"])
scaled_df.head()

total_datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.05,
    height_shift_range=0.05,
    rescale=1./255,
    shear_range=0.05,
    brightness_range=[0.1, 1.5],
    horizontal_flip=True,
    vertical_flip=True
)

"""1.Predictive Modelling

Splitting the data into test and train sets
"""

# import tensorflow
# train,test=train_test_split(data,test_size=0.3,random_state=0,stratify=data['Anaemic'])
# train_X=train[train.columns[:-1]]
# train_Y=train[train.columns[-1:]]
# test_X=test[test.columns[:-1]]
# test_Y=test[test.columns[-1:]]
# X=data[data.columns[:-1]]
# Y=data['Anaemic']
X=data[[ 'sex_encoded', '   %Red Pixel', '%Green pixel', '%Blue pixel', 'Hb']]
y=data["anaemic_encoded"]
train_X,test_X,train_Y,test_Y=train_test_split(X,y,test_size=0.3,random_state=0)
train_X,val_X,train_Y,val_Y=train_test_split(train_X,train_Y,test_size=0.3,random_state=0)
len(train_X), len(train_Y), len(test_X), len(test_Y)

kf =KFold(n_splits=5, shuffle=True, random_state=42)

cnt = 1
# split()  method generate indices to split data into training and test set.
for train_index, test_index in kf.split(train_X, train_Y):
    print(f'Fold:{cnt}, Train set: {len(train_index)}, Test set:{len(test_index)}')
    cnt += 1

train_X.head()

train_Y.head()

test_X.head()

test_Y.head()

"""Radial Support Vector Machines(rbf-SVM)


"""

from sklearn.metrics import ConfusionMatrixDisplay
rbf=svm.SVC(kernel='rbf',C=1,gamma=0.1)
rbf.fit(train_X,train_Y)

# Evaluate by means of a confusion matrix
disp = ConfusionMatrixDisplay.from_estimator(rbf, test_X, test_Y,
                                 cmap=plt.cm.Blues,
                                 normalize='true')
disp.ax_.set_title('Confusion matrix for Radial SVM')
plt.show()

# Generate predictions
y_pred = rbf.predict(test_X)
y_pred_val = rbf.predict(val_X)
tn, fp, fn, tp = confusion_matrix(test_Y, y_pred).ravel()
# Evaluate by means of accuracy
accuracy = accuracy_score(test_Y, y_pred)
print(f'Accuracy for rbf SVM is: {accuracy}')

val_accuracy = accuracy_score(val_Y, y_pred_val)
print(f'Accuracy Validation for rbf SVM is: {val_accuracy}')

# plt.plot(accuracy)
# plt.plot(val_accuracy)
# plt.title('model accuracy')
# plt.ylabel('accuracy')
# plt.xlabel('epoch')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.show()
target_names = ['no 0', 'yes 1']
print(classification_report(test_Y,y_pred, target_names=target_names))

"""Linear Support Vector Machine(linear-SVM)


"""

svc=svm.SVC(kernel='linear',C=0.1,gamma=0.1)
svc.fit(train_X,train_Y)

# Evaluate by means of a confusion matrix
disp = ConfusionMatrixDisplay.from_estimator(svc, test_X, test_Y,
                                 cmap=plt.cm.Blues,
                                 normalize='true')
disp.ax_.set_title('Confusion matrix for linear SVM')
plt.show()

# Generate predictions
y_pred = svc.predict(test_X)
y_pred_val = svc.predict(val_X)
tn, fp, fn, tp = confusion_matrix(test_Y, y_pred).ravel()
# Evaluate by means of accuracy
accuracy = accuracy_score(test_Y, y_pred)
print(f'Accuracy for linear SVM is: {accuracy}')

val_accuracy = accuracy_score(val_Y, y_pred_val)
print(f'Accuracy Validation for linear SVM is: {val_accuracy}')

# plt.plot(accuracy)
# plt.plot(val_accuracy)
# plt.title('model accuracy')
# plt.ylabel('accuracy')
# plt.xlabel('epoch')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.show()
target_names = ['no 0', 'yes 1']
print(classification_report(test_Y,y_pred, target_names=target_names))

class_weight = {0: 1.,
                1: 3.04}
C_range=list(np.arange(0.2,1.9,0.1))
acc_scoreLSVM=[]
for c in C_range:
    print(c)
    svc = svm.SVC(kernel='linear', C=c,max_iter=500000,class_weight=class_weight)
    scores = cross_val_score(svc,train_X, train_Y, cv= kf, scoring="accuracy")
    print(scores)
    acc_scoreLSVM.append(scores.mean())
print(acc_scoreLSVM)

"""Logistic Regression


"""

lr = LogisticRegression()
lr.fit(train_X,train_Y)

# Evaluate by means of a confusion matrix
confusionmatrix = plot_confusion_matrix(lr, test_X, test_Y,
                                 normalize='true')
plt.title('Confusion matrix for Logistic Regression')
plt.show(confusionmatrix)
plt.show()

# Generate predictions
y_pred = lr.predict(test_X)
y_pred_val = lr.predict(val_X)
tn, fp, fn, tp = confusion_matrix(test_Y, y_pred).ravel()
# Evaluate by means of accuracy
accuracy = accuracy_score(test_Y, y_pred)
print(f'Accuracy for Logistic Regression is: {accuracy}')

val_accuracy = accuracy_score(val_Y, y_pred_val)
print(f'Accuracy Validation for Logistic Regression is: {val_accuracy}')

# plt.plot(accuracy)
# plt.plot(val_accuracy)
# plt.title('model accuracy')
# plt.ylabel('accuracy')
# plt.xlabel('epoch')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.show()
target_names = ['no 0', 'yes 1']
print(classification_report(test_Y,y_pred, target_names=target_names))

plt.figure(figsize=(10, 6))
plt.plot(C_range, acc_scoreLSVM, marker='o')
plt.xlabel('C Value')
plt.ylabel('Average Accuracy Score')
plt.title('Linear SVM Accuracy for different C values')
plt.grid(True)
plt.show()

score = cross_val_score(linear_model.LogisticRegression(random_state= 42), train_X, train_Y, cv= kf, scoring="accuracy")
print(f'Scores for each fold are: {score}')
print(f'Average score: {"{:.2f}".format(score.mean())}')

"""Decision Tree


"""

dt=DecisionTreeClassifier()
dt.fit(train_X,train_Y)

# Evaluate by means of a confusion matrix
disp = ConfusionMatrixDisplay.from_estimator(dt, test_X, test_Y,
                                 cmap=plt.cm.Blues,
                                 normalize='true')
disp.ax_.set_title('Confusion matrix for the Decision Tree')
plt.show()

# Generate predictions
y_pred = dt.predict(test_X)
y_pred_val = dt.predict(val_X)
tn, fp, fn, tp = confusion_matrix(test_Y, y_pred).ravel()
# Evaluate by means of accuracy
accuracy = accuracy_score(test_Y, y_pred)
print(f'Accuracy for the Decision Tree is: {accuracy}')

val_accuracy = accuracy_score(val_Y, y_pred_val)
print(f'Accuracy Validation for the Decision Tree is: {val_accuracy}')

# plt.plot(accuracy)
# plt.plot(val_accuracy)
# plt.title('model accuracy')
# plt.ylabel('accuracy')
# plt.xlabel('epoch')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.show()
target_names = ['no 0', 'yes 1']
print(classification_report(test_Y,y_pred, target_names=target_names))

max_depth = [1,2,3,4,5,6,7,8,9,10]

for val in max_depth:
    score = cross_val_score(tree.DecisionTreeClassifier(max_depth= val, random_state= 42), train_X, train_Y, cv= kf, scoring="accuracy")
    print(f'Average score({val}): {"{:.3f}".format(score.mean())}')

"""K-Nearest Neighbours(KNN)


"""

knn=KNeighborsClassifier()
knn.fit(train_X,train_Y)

# Evaluate by means of a confusion matrix
disp = ConfusionMatrixDisplay.from_estimator(knn, test_X, test_Y,
                                 cmap=plt.cm.Blues,
                                 normalize='true')
disp.ax_.set_title('Confusion matrix for the KNN')
plt.show()

# Generate predictions
y_pred = knn.predict(test_X)
y_pred_val = knn.predict(val_X)
tn, fp, fn, tp = confusion_matrix(test_Y, y_pred).ravel()
# Evaluate by means of accuracy
accuracy = accuracy_score(test_Y, y_pred)
print(f'Accuracy for the KNN is: {accuracy}')

val_accuracy = accuracy_score(val_Y, y_pred_val)
print(f'Accuracy Validation for the KNN is: {val_accuracy}')

# plt.plot(accuracy)
# plt.plot(val_accuracy)
# plt.title('model accuracy')
# plt.ylabel('accuracy')
# plt.xlabel('epoch')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.show()
target_names = ['no 0', 'yes 1']
print(classification_report(test_Y,y_pred, target_names=target_names))

knn_5 = KNeighborsClassifier(n_neighbors=5)


# fit the model to the training set
knn_5.fit(train_X,train_Y)


# predict on the test-set
y_pred_5 = knn_5.predict(test_X)


print('Model accuracy score with k=5 : {0:0.4f}'. format(accuracy_score(test_Y, y_pred_5)))

"""Gaussian Naive Bayes


"""

gnb=GaussianNB()
gnb.fit(train_X,train_Y)

# Evaluate by means of a confusion matrix
disp = ConfusionMatrixDisplay.from_estimator(gnb, test_X, test_Y,
                                 cmap=plt.cm.Blues,
                                 normalize='true')
disp.ax_.set_title('Confusion matrix for the NaiveBayes')
plt.show()

# Generate predictions
y_pred = gnb.predict(test_X)
y_pred_val = gnb.predict(val_X)
tn, fp, fn, tp = confusion_matrix(test_Y, y_pred).ravel()
# Evaluate by means of accuracy
accuracy = accuracy_score(test_Y, y_pred)
print(f'Accuracy for the NaiveBayes is: {accuracy}')

val_accuracy = accuracy_score(val_Y, y_pred_val)
print(f'Accuracy Validation for the NaiveBayes is: {val_accuracy}')

# plt.plot(accuracy)
# plt.plot(val_accuracy)
# plt.title('model accuracy')
# plt.ylabel('accuracy')
# plt.xlabel('epoch')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.show()
target_names = ['no 0', 'yes 1']
print(classification_report(test_Y,y_pred, target_names=target_names))

"""Random Forests


"""

rfc=RandomForestClassifier(n_estimators=100)
rfc.fit(train_X,train_Y)

# Evaluate by means of a confusion matrix
# confusionmatrix = plot_confusion_matrix(rfc, test_X, test_Y,
#                                  normalize='true')
# plt.title('Confusion matrix for the Random Forests')
# plt.show(confusionmatrix)
# plt.show()
disp = ConfusionMatrixDisplay.from_estimator(rfc, test_X, test_Y,
                                 cmap=plt.cm.Blues,
                                 normalize='true')
disp.ax_.set_title('Confusion matrix for the Random Forests')
plt.show()

# Generate predictions
y_pred = rfc.predict(test_X)
y_pred_val = rfc.predict(val_X)
tn, fp, fn, tp = confusion_matrix(test_Y, y_pred).ravel()
# Evaluate by means of accuracy
accuracy = accuracy_score(test_Y, y_pred)
print(f'Accuracy for the Random Forests is: {accuracy}')

val_accuracy = accuracy_score(val_Y, y_pred_val)
print(f'Accuracy Validation for the Random Forests is: {val_accuracy}')

# plt.plot(accuracy)
# plt.plot(val_accuracy)
# plt.title('model accuracy')
# plt.ylabel('accuracy')
# plt.xlabel('epoch')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.show()
target_names = ['no 0', 'yes 1']
print(classification_report(test_Y,y_pred, target_names=target_names))

score = cross_val_score(ensemble.RandomForestClassifier(random_state= 42),train_X, train_Y, cv= kf, scoring="accuracy")
print(f'Scores for each fold are: {score}')
print(f'Average score: {"{:.2f}".format(score.mean())}')

"""Cross Validation


"""

kfold = KFold(n_splits=10) # k=10, split the data into 10 equal parts
cv_mean=[]
accuracy=[]
std=[]
precision = []
recall = []
f1score = []
minimum = []
maximum = []
classifiers=[
    'Linear Svm',
    'Radial Svm',
    'Logistic Regression',
    'KNN',
    'Decision Tree',
    'Naive Bayes',
    'Random Forest'
]
models=[
    svm.SVC(kernel='linear',probability=True),
    svm.SVC(kernel='rbf',probability=True),
    LogisticRegression(),
    KNeighborsClassifier(n_neighbors=9),
    DecisionTreeClassifier(),
    GaussianNB(),
    RandomForestClassifier(n_estimators=100)
]
for index,model in enumerate(models):
    cv_result = cross_val_score(model,train_X,train_Y, cv = kfold,scoring = "accuracy")
    cv_mean.append(cv_result.mean())
    std.append(cv_result.std())
    minimum.append(cv_result.min())
    maximum.append(cv_result.max())
    model.fit(train_X, train_Y)
    y_score = model.predict(train_X)
    acc = metrics.accuracy_score(y_true = train_Y, y_pred = y_score)
    pre = metrics.precision_score(y_true = train_Y, y_pred = y_score)
    rec = metrics.recall_score(y_true = train_Y, y_pred = y_score)
    f1 = metrics.f1_score(y_true = train_Y, y_pred = y_score)
    accuracy.append(acc)
    precision.append(pre)
    recall.append(rec)
    f1score.append(f1)
    target_names = ['Non-Anaemic 0', 'Anaemic 1']
    report1 = classification_report(train_Y,y_score, target_names=target_names,  output_dict=True)
    display.display(pd.DataFrame(report1))
    df = pd.DataFrame(report1)
    plt.figure(figsize=(20,20))
    df.iloc[:3, :2].T.plot(kind='bar')
    plt.legend(loc='lower right')
    plt.title(classifiers[index])
    plt.show()
    y_prob = model.predict_proba(test_X)[:,1]
    false_positive_rate, true_positive_rate, thresholds = roc_curve(test_Y, y_prob)
    roc_auc = auc(false_positive_rate, true_positive_rate)
    plt.figure(figsize=(6,6))
    plt.title('ROC Curve For '+ classifiers[index])
    plt.plot(false_positive_rate,true_positive_rate, color='red',label = 'AUC = %0.2f' % roc_auc)
    plt.legend(loc = 'lower right')
    plt.plot([0, 1], [0, 1],linestyle='--')
    plt.axis('tight')
    plt.ylabel('True Positive Rate')
    plt.xlabel('False Positive Rate')
    plt.show()
    print("\n")
    print("*********************************************************************************************")
    print("\n")

# Logistic regression
modelLR = LogisticRegression()
modelLR.fit(train_X,train_Y)
y_pred_prob_lr = modelLR.predict_proba(test_X)[:,1]
fpr_lr, tpr_lr, thresholds_lr = roc_curve(test_Y, y_pred_prob_lr)
roc_auc_lr = auc(fpr_lr, tpr_lr)
precision_lr, recall_lr, th_lr = precision_recall_curve(test_Y, y_pred_prob_lr)

# SVM with rbf
modelSVMrbf=svm.SVC(kernel='rbf', probability=True)
modelSVMrbf.fit(train_X,train_Y)
y_pred_prob_SVMrbf = modelSVMrbf.predict_proba(test_X)[:,1]
fpr_SVMrbf, tpr_SVMrbf, thresholds_SVMrbf = roc_curve(test_Y, y_pred_prob_SVMrbf)
roc_auc_SVMrbf = auc(fpr_SVMrbf, tpr_SVMrbf)
precision_SVMrbf, recall_SVMrbf, th_SVMrbf = precision_recall_curve(test_Y, y_pred_prob_SVMrbf)

# SVM with linear
modelSVMlinear=svm.SVC(kernel='linear', probability=True)
modelSVMlinear.fit(train_X,train_Y)
y_pred_prob_SVMlinear = modelSVMlinear.predict_proba(test_X)[:,1]
fpr_SVMlinear, tpr_SVMlinear, thresholds_SVMlinear = roc_curve(test_Y, y_pred_prob_SVMlinear)
roc_auc_SVMlinear = auc(fpr_SVMlinear, tpr_SVMlinear)
precision_SVMlinear, recall_SVMlinear, th_SVMlinear = precision_recall_curve(test_Y, y_pred_prob_SVMlinear)

# KNN
modelKNN = KNeighborsClassifier(n_neighbors=9)
modelKNN.fit(train_X,train_Y)
y_pred_prob_KNN = modelKNN.predict_proba(test_X)[:,1]
fpr_KNN, tpr_KNN, thresholds_KNN = roc_curve(test_Y, y_pred_prob_KNN)
roc_auc_KNN = auc(fpr_KNN, tpr_KNN)
precision_KNN, recall_KNN, th_KNN = precision_recall_curve(test_Y, y_pred_prob_KNN)


# Decision Tree
modelTree=DecisionTreeClassifier()
modelTree.fit(train_X,train_Y)
y_pred_prob_Tree = modelTree.predict_proba(test_X)[:,1]
fpr_Tree, tpr_Tree, thresholds_Tree = roc_curve(test_Y, y_pred_prob_Tree)
roc_auc_Tree = auc(fpr_Tree, tpr_Tree)
precision_Tree, recall_Tree, th_Tree = precision_recall_curve(test_Y, y_pred_prob_Tree)

# Random forest
modelRF= RandomForestClassifier(n_estimators=100,random_state=0)
modelRF.fit(train_X,train_Y)
y_pred_prob_rf = modelRF.predict_proba(test_X)[:,1]
fpr_rf, tpr_rf, thresholds_rf = roc_curve(test_Y, y_pred_prob_rf)
roc_auc_rf = auc(fpr_rf, tpr_rf)
precision_rf, recall_rf, th_rf = precision_recall_curve(test_Y, y_pred_prob_rf)


# Naive Bayes
modelNB= GaussianNB()
modelNB.fit(train_X,train_Y)
y_pred_prob_nb = modelNB.predict_proba(test_X)[:,1]
fpr_nb, tpr_nb, thresholds_nb = roc_curve(test_Y, y_pred_prob_nb)
roc_auc_nb = auc(fpr_nb, tpr_nb)
precision_nb, recall_nb, th_nb = precision_recall_curve(test_Y, y_pred_prob_nb)

# Plot ROC curve
plt.plot([0, 1], [0, 1], 'k--')
plt.plot(fpr_lr, tpr_lr, label='Log Reg (area = %0.3f)' % roc_auc_lr)
plt.plot(fpr_SVMrbf, tpr_SVMrbf, label='SVM rbf (area = %0.3f)' % roc_auc_SVMrbf)
plt.plot(fpr_SVMlinear, tpr_SVMlinear, label='SVM linear (area = %0.3f)' % roc_auc_SVMlinear)
plt.plot(fpr_KNN, tpr_KNN, label='KNN (area = %0.3f)' % roc_auc_KNN)
plt.plot(fpr_Tree, tpr_Tree, label='Tree (area = %0.3f)' % roc_auc_Tree)
plt.plot(fpr_rf, tpr_rf, label='RF (area = %0.3f)' % roc_auc_rf)
plt.plot(fpr_nb, tpr_nb, label='NB (area = %0.3f)' % roc_auc_nb)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC curves from the investigated models')
plt.legend(loc='best')
plt.show()

plt.plot([1, 0], [0, 1], 'k--')
plt.plot(recall_lr, precision_lr, label='Log Reg')
plt.plot(recall_SVMrbf, precision_SVMrbf, label='SVM rbf')
plt.plot(recall_SVMlinear, precision_SVMlinear, label='SVM linear')
plt.plot(recall_KNN, precision_KNN, label='KNN')
plt.plot(recall_Tree, precision_Tree, label='Tree')
plt.plot(recall_rf, precision_rf, label='RF')
plt.plot(recall_nb, precision_nb, label='NB')
plt.title('Precision vs. Recall')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.legend(loc='best')
plt.show()

new_models_dataframe2=pd.DataFrame({
    'CV Mean':cv_mean,
    "Standard deviation":std,
    'Maximum':maximum,
    'Minimum':minimum,
    'Accuracy':accuracy,
    'Precision':precision,
    'Recall':recall,
    'F1 Score':f1score,
},
    index=classifiers
)
new_models_dataframe2

new_models_dataframe2.plot(kind="bar",stacked=True)
plt.plot(new_models_dataframe2.values)
plt.xticks(range(len(new_models_dataframe2)),labels=new_models_dataframe2.index)
plt.xlabel("Classifiers")
plt.ylabel("% of Total")
plt.title("Classifiers Report")

new_models_dataframe2['CV Mean'].plot.barh(width=0.8)
plt.title('Average CV Mean Accuracy')
fig=plt.gcf()
fig.set_size_inches(8,5)
plt.show()

f,ax=plt.subplots(3,3,figsize=(12,10))
y_pred = cross_val_predict(svm.SVC(kernel='rbf'),val_X,val_Y,cv=10)
sns.heatmap(confusion_matrix(val_Y,y_pred),ax=ax[0,0],annot=True,fmt='2.0f')
ax[0,0].set_title('Matrix for rbf-SVM')
y_pred = cross_val_predict(svm.SVC(kernel='linear'),val_X,val_Y,cv=10)
sns.heatmap(confusion_matrix(val_Y,y_pred),ax=ax[0,1],annot=True,fmt='2.0f')
ax[0,1].set_title('Matrix for Linear-SVM')
y_pred = cross_val_predict(KNeighborsClassifier(n_neighbors=5),val_X,val_Y,cv=10)
sns.heatmap(confusion_matrix(val_Y,y_pred),ax=ax[0,2],annot=True,fmt='2.0f')
ax[0,2].set_title('Matrix for KNN')
y_pred = cross_val_predict(RandomForestClassifier(n_estimators=100),val_X,val_Y,cv=10)
sns.heatmap(confusion_matrix(val_Y,y_pred),ax=ax[1,0],annot=True,fmt='2.0f')
ax[1,0].set_title('Matrix for Random-Forests')
y_pred = cross_val_predict(LogisticRegression(),val_X,val_Y,cv=10)
sns.heatmap(confusion_matrix(val_Y,y_pred),ax=ax[1,1],annot=True,fmt='2.0f')
ax[1,1].set_title('Matrix for Logistic Regression')
y_pred = cross_val_predict(DecisionTreeClassifier(),val_X,val_Y,cv=10)
sns.heatmap(confusion_matrix(val_Y,y_pred),ax=ax[1,2],annot=True,fmt='2.0f')
ax[1,2].set_title('Matrix for Decision Tree')
y_pred = cross_val_predict(GaussianNB(),val_X,val_Y,cv=10)
sns.heatmap(confusion_matrix(val_Y,y_pred),ax=ax[2,0],annot=True,fmt='2.0f')
ax[2,0].set_title('Matrix for Naive Bayes')
plt.subplots_adjust(hspace=0.2,wspace=0.2)
plt.show()

"""Ensembling"""

from sklearn.ensemble import VotingClassifier
ensemble_lin_rbf=VotingClassifier(estimators=[('KNN',KNeighborsClassifier(n_neighbors=5)),
                                              ('RBF',svm.SVC(probability=True,kernel='rbf',C=0.5,gamma=0.1)),
                                              ('RFor',RandomForestClassifier(n_estimators=500,random_state=0)),
                                              ('LR',LogisticRegression(C=0.05)),
                                              ('DT',DecisionTreeClassifier(random_state=0)),
                                              ('NB',GaussianNB()),
                                              ('svm',svm.SVC(kernel='linear',probability=True))
                                             ],
                       voting='soft').fit(train_X,train_Y)
print('The accuracy for ensembled model is:',ensemble_lin_rbf.score(test_X,test_Y))
cross=cross_val_score(ensemble_lin_rbf,val_X,val_Y, cv = 10,scoring = "accuracy")
print('The cross validated score is :',cross.mean())

"""Boosting"""

from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier(n_estimators=200,random_state=0,learning_rate=0.1)
result=cross_val_score(ada,val_X,val_Y,cv=10,scoring='accuracy')
print('The cross validated score for AdaBoost is:',result.mean())

"""GradientBoostingClassifier"""

from sklearn.ensemble import GradientBoostingClassifier
grad=GradientBoostingClassifier(n_estimators=500,random_state=0,learning_rate=0.1)
result=cross_val_score(grad,val_X,val_Y,cv=10,scoring='accuracy')
print('The cross validated score for Gradient Boosting is:',result.mean())

"""XGBoost"""

xgboost=xg.XGBClassifier(n_estimators=900,learning_rate=0.1)
result=cross_val_score(xgboost,val_X,val_Y,cv=10,scoring='accuracy')
print('The cross validated score for XGBoost is:',result.mean())

"""### Test with Custom Input

To test the model with your own data, please provide the following numerical features. Remember that the model was trained on these specific features, not raw images.

*   **%Red Pixel**
*   **%Green pixel**
*   **%Blue pixel**
*   **Hb** (Hemoglobin level)
*   **Sex** (Enter 'M' for Male or 'F' for Female)
"""

import pandas as pd
import numpy as np

# Assuming rfc (RandomForestClassifier) is the desired model for prediction, as it showed high accuracy.
# If you prefer a different model, replace `rfc` with the variable name of that model (e.g., `lr` for Logistic Regression).

# Collect user input
red_pixel = float(input("Enter %Red Pixel: "))
green_pixel = float(input("Enter %Green pixel: "))
blue_pixel = float(input("Enter %Blue pixel: "))
hb = float(input("Enter Hb (Hemoglobin) level: "))
sex_input = input("Enter Sex (M/F): ").upper()

# Encode Sex input
sex_encoded_val = 1 if sex_input == 'M' else (0 if sex_input == 'F' else -1) # -1 for invalid input

if sex_encoded_val == -1:
    print("Invalid Sex input. Please enter 'M' or 'F'.")
else:
    # Create a DataFrame for the single prediction, matching the training features' structure and column names
    input_data = pd.DataFrame([[sex_encoded_val, red_pixel, green_pixel, blue_pixel, hb]],
                              columns=['sex_encoded', '   %Red Pixel', '%Green pixel', '%Blue pixel', 'Hb'])

    # Make prediction using the trained Random Forest Classifier (rfc)
    # Ensure the rfc model is available in the kernel from previous executions.
    if 'rfc' in globals():
        prediction = rfc.predict(input_data)
        prediction_proba = rfc.predict_proba(input_data)

        if prediction[0] == 1:
            print(f"\nPrediction: Anaemic (Probability: {prediction_proba[0][1]:.2f})")
        else:
            print(f"\nPrediction: Non-Anaemic (Probability: {prediction_proba[0][0]:.2f})")
    else:
        print("Error: RandomForestClassifier model 'rfc' not found. Please ensure the model cell has been run.")

import cv2
import matplotlib.pyplot as plt
from skimage.feature import local_binary_pattern
from PIL import Image
import numpy as np

def extract_advanced_features(image_path):
    # Load image using OpenCV
    img = cv2.imread(image_path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 1. Color Histogram (Red Channel as example)
    hist_red = cv2.calcHist([img], [2], None, [256], [0, 256])

    # 2. Edge Detection (Canny)
    edges = cv2.Canny(img_gray, 100, 200)

    # 3. Texture Analysis (LBP)
    radius = 3
    n_points = 8 * radius
    lbp = local_binary_pattern(img_gray, n_points, radius, method='uniform')

    # Visualization
    plt.figure(figsize=(15, 5))
    plt.subplot(1, 4, 1); plt.imshow(img_rgb); plt.title('Original')
    plt.subplot(1, 4, 2); plt.plot(hist_red, color='red'); plt.title('Red Hist')
    plt.subplot(1, 4, 3); plt.imshow(edges, cmap='gray'); plt.title('Edges')
    plt.subplot(1, 4, 4); plt.imshow(lbp, cmap='gray'); plt.title('LBP Texture')
    plt.show()

# Example usage with the last uploaded image
if 'filename' in globals():
    extract_advanced_features(filename)
else:
    print('Please upload an image first using the previous cell.')

from PIL import Image
import numpy as np
import pandas as pd
from google.colab import files
import io
import matplotlib.pyplot as plt

def predict_from_image_improved():
    if 'rfc' not in globals():
        print('Error: RandomForestClassifier model rfc not found.')
        return

    print('Please upload a clear image of the sample.')
    uploaded = files.upload()

    for filename in uploaded.keys():
        img = Image.open(io.BytesIO(uploaded[filename])).convert('RGB')
        width, height = img.size

        # Crop to the center 50% to avoid background noise/borders
        left = width * 0.25
        top = height * 0.25
        right = width * 0.75
        bottom = height * 0.75
        img_cropped = img.crop((left, top, right, bottom))

        img_array = np.array(img_cropped)

        # Calculate mean RGB
        avg_red = img_array[:,:,0].mean()
        avg_green = img_array[:,:,1].mean()
        avg_blue = img_array[:,:,2].mean()

        # Training data for '%Red Pixel' was roughly in the 38-54 range
        # Formula: (Channel_Mean / Total_RGB_Sum) * 100
        total_rgb = avg_red + avg_green + avg_blue
        p_red = (avg_red / total_rgb) * 100
        p_green = (avg_green / total_rgb) * 100
        p_blue = (avg_blue / total_rgb) * 100

        print(f'\n--- Extracted Features ---')
        print(f'%Red: {p_red:.2f}, %Green: {p_green:.2f}, %Blue: {p_blue:.2f}')

        hb = float(input('Enter Hb level (e.g., 9.1 or 14.5): '))
        sex = input('Enter Sex (M/F): ').upper()
        s_enc = 1 if sex == 'M' else 0

        input_df = pd.DataFrame([[s_enc, p_red, p_green, p_blue, hb]],
                                columns=['sex_encoded', '   %Red Pixel', '%Green pixel', '%Blue pixel', 'Hb'])

        pred = rfc.predict(input_df)[0]
        prob = rfc.predict_proba(input_df)[0]

        # Show the cropped area used for analysis
        plt.imshow(img_cropped)
        plt.title(f'Analyzed Region\nResult: {"Anaemic" if pred==1 else "Non-Anaemic"}')
        plt.axis('off')
        plt.show()

        if pred == 1:
            print(f'PREDICTION: ANAEMIC (Confidence: {prob[1]:.2f})')
        else:
            print(f'PREDICTION: NON-ANAEMIC (Confidence: {prob[0]:.2f})')

predict_from_image_improved()

# Re-running the improved prediction function
predict_from_image_improved()

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Prepare data using only RGB features
X_vision = data[['   %Red Pixel', '%Green pixel', '%Blue pixel']]
y_vision = data['anaemic_encoded']

# Split the data
train_X_v, test_X_v, train_Y_v, test_Y_v = train_test_split(X_vision, y_vision, test_size=0.3, random_state=42)

# Train the 'Vision Only' model
rfc_vision_only = RandomForestClassifier(n_estimators=100, random_state=42)
rfc_vision_only.fit(train_X_v, train_Y_v)

print(f'Vision-Only Model Accuracy: {rfc_vision_only.score(test_X_v, test_Y_v):.2f}')

def predict_vision_only():
    print('Upload an image for Vision-Only Prediction (No Hb required)')
    uploaded = files.upload()

    for filename in uploaded.keys():
        img = Image.open(io.BytesIO(uploaded[filename])).convert('RGB')
        width, height = img.size
        img_cropped = img.crop((width * 0.25, height * 0.25, width * 0.75, height * 0.75))
        img_array = np.array(img_cropped)

        avg_red, avg_green, avg_blue = img_array[:,:,0].mean(), img_array[:,:,1].mean(), img_array[:,:,2].mean()
        total_rgb = avg_red + avg_green + avg_blue

        p_red = (avg_red / total_rgb) * 100
        p_green = (avg_green / total_rgb) * 100
        p_blue = (avg_blue / total_rgb) * 100

        input_df = pd.DataFrame([[p_red, p_green, p_blue]],
                                columns=['   %Red Pixel', '%Green pixel', '%Blue pixel'])

        pred = rfc_vision_only.predict(input_df)[0]
        prob = rfc_vision_only.predict_proba(input_df)[0]

        plt.imshow(img_cropped)
        plt.title(f'Vision Prediction: {"Anaemic" if pred==1 else "Non-Anaemic"}')
        plt.axis('off')
        plt.show()

        print(f'RESULT: {"ANAEMIC" if pred==1 else "NON-ANAEMIC"}')
        print(f'Confidence based on Pixels: {max(prob):.2f}')

predict_vision_only()

import matplotlib.pyplot as plt
import pandas as pd

if 'rfc' in globals():
    # Get feature importances from the trained Random Forest
    importances = rfc.feature_importances_
    feature_names = ['sex_encoded', '   %Red Pixel', '%Green pixel', '%Blue pixel', 'Hb']

    # Create a series for visualization
    feat_importances = pd.Series(importances, index=feature_names)

    plt.figure(figsize=(10,6))
    feat_importances.sort_values().plot(kind='barh', color='skyblue')
    plt.title('Feature Importance in Anemia Prediction')
    plt.xlabel('Relative Importance Score')
    plt.show()

    print("Numerical Importance Scores:")
    print(feat_importances.sort_values(ascending=False))
else:
    print('RandomForest model (rfc) not found in memory.')

"""### Hb Sensitivity Test
Use the cell below to see how the model reacts to the **exact same image data** but with different Hemoglobin levels. This will confirm if the RGB pixels have any influence at all or if the model is just a 'Hemoglobin calculator'.
"""

def test_hb_sensitivity(p_red, p_green, p_blue, sex_enc):
    hb_range = np.arange(8.0, 16.0, 0.5)
    results = []

    for hb in hb_range:
        input_df = pd.DataFrame([[sex_enc, p_red, p_green, p_blue, hb]],
                                columns=['sex_encoded', '   %Red Pixel', '%Green pixel', '%Blue pixel', 'Hb'])
        prob = rfc.predict_proba(input_df)[0][1] # Probability of being Anaemic
        results.append(prob)

    plt.figure(figsize=(10,5))
    plt.plot(hb_range, results, marker='o', color='red')
    plt.axhline(y=0.5, color='gray', linestyle='--')
    plt.title('Effect of Hb Level on Anaemia Probability (Fixed Image Data)')
    plt.xlabel('Input Hemoglobin (Hb)')
    plt.ylabel('Probability of Anaemia')
    plt.grid(True)
    plt.show()

# Example using the last extracted pixels from your previous run
# %Red: 41.72, %Green: 30.16, %Blue: 28.12, Sex: Male (1)
test_hb_sensitivity(41.72, 30.16, 28.12, 1)

"""### Testing with Image Input (and Manual Clinical Data)

This section allows you to test the model by providing an image. The code will extract the average Red, Green, and Blue pixel percentages from your uploaded image. However, please remember to **manually input the Hemoglobin (Hb) level and the patient's Sex**, as these cannot be derived from the image itself.

**Instructions:**
1.  Run the cell below.
2.  Upload an image file (e.g., a blood sample image).
3.  Enter the Hb (Hemoglobin) level and Sex (M/F) when prompted.
"""

from PIL import Image
import numpy as np
import pandas as pd
from google.colab import files
import io

# Assuming rfc (RandomForestClassifier) is the desired model for prediction.
# Ensure the rfc model is available in the kernel from previous executions.

if 'rfc' not in globals():
    print("Error: RandomForestClassifier model 'rfc' not found. Please ensure the model training cells have been run.")
else:
    print("Please upload your image file.")
    uploaded = files.upload()

    for filename in uploaded.keys():
        try:
            img = Image.open(io.BytesIO(uploaded[filename]))

            # Convert image to RGB (if not already)
            img = img.convert('RGB')

            # Convert image to numpy array
            img_array = np.array(img)

            # Calculate average RGB values
            avg_red = img_array[:,:,0].mean()
            avg_green = img_array[:,:,1].mean()
            avg_blue = img_array[:,:,2].mean()

            # Scale RGB values to a 0-100 percentage range (if needed, based on training data)
            # The training data has values like 47.6372 for %Red Pixel, so we will use the raw mean.
            # If the training data was normalized differently, this step would need adjustment.
            percent_red_pixel = (avg_red / 255) * 100
            percent_green_pixel = (avg_green / 255) * 100
            percent_blue_pixel = (avg_blue / 255) * 100

            print(f"\nExtracted %Red Pixel: {percent_red_pixel:.2f}")
            print(f"Extracted %Green pixel: {percent_green_pixel:.2f}")
            print(f"Extracted %Blue pixel: {percent_blue_pixel:.2f}")

            # Get manual input for Hb and Sex
            hb = float(input("Enter Hb (Hemoglobin) level: "))
            sex_input = input("Enter Sex (M/F): ").upper()

            sex_encoded_val = 1 if sex_input == 'M' else (0 if sex_input == 'F' else -1)

            if sex_encoded_val == -1:
                print("Invalid Sex input. Please enter 'M' or 'F'.")
            else:
                # Create a DataFrame for the single prediction
                input_data = pd.DataFrame([[sex_encoded_val, percent_red_pixel, percent_green_pixel, percent_blue_pixel, hb]],
                                          columns=['sex_encoded', '   %Red Pixel', '%Green pixel', '%Blue pixel', 'Hb'])

                prediction = rfc.predict(input_data)
                prediction_proba = rfc.predict_proba(input_data)

                if prediction[0] == 1:
                    print(f"\nPrediction: Anaemic (Probability: {prediction_proba[0][1]:.2f})")
                else:
                    print(f"\nPrediction: Non-Anaemic (Probability: {prediction_proba[0][0]:.2f})")

        except Exception as e:
            print(f"An error occurred during image processing or prediction: {e}")